# Site settings
title: null pointers
email: hakim.hanif@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hakimhanif.com" # the base hostname & protocol for your site
twitter_username: hhanif
github_username:  hahan

# Build settings
markdown: kramdown

permalink: /:year/:month/:title/
